### ISSUE TITLE
new config file not working 

### ISSUE THREAD

**Issue by vrennie** [TORCH-Consortium/MAGMA#225] opened 2024-09-26 10:58 UTC
Hi @abhi18av,

Yesterday I created the sandbox_vm.config file and merged it into master.

However, neither Simone nor me (running through Tower) can get the pipeline to run using this config.

<img width="991" alt="image" src="https://github.com/user-attachments/assets/8175a648-b4d5-485d-8d58-b452348bfe98">

Any ideas?

**Comment by abhi18av** [comment] 2024-09-26 15:03
@vrennie I think that there might be some 

> Yesterday I created the sandbox_vm.config file and merged it into master.

Dear @mdediegofuertes  and @vrennie , I highly recommend that changes to the master not be merged before local testing otherwise, it becomes a time-sink for multiple people involved.

====

I took a look at the code now https://github.com/TORCH-Consortium/MAGMA/pull/223, and the profile needs to be added in the `nextflow.config` files as shown below.

https://github.com/TORCH-Consortium/MAGMA/blob/bf355d0ca09f5160ca2894d6c997de56217aeacf/nextflow.config#L65

====

That being said, by including institution specific configuration in the pipeline, we are not moving in the right direction since it'll create a new dependency and when they have new VMs or something goes wrong with the IT or Azure setup, we have to accommodate the changes in pipeline config as well. They can always override the configuraiton using `-c` command.


Marking this issue as closed since this is not a bug, but rather a design choice.

**Closed by abhi18av** 2024-09-26 15:03 UTC
